#!/bin/sh

~/git/NXCompile/NXCompile -s -n -o ~/.XCompose ~/.XCompile.d/*.txt

cat >> ~/.XCompose << EOT

# Include the standard xcompose bindings
# (This needs to be at the end for fcitx)
include "%L"

# By the way, this file was automatically generated by
# ~/.XCompile.d/regen.sh
EOT

fixkeys
killall -HUP fcitx fcitx5
