#!/bin/sh

# This file gets run on the ssh target, as long as PermitUserRC isn't disabled
# in the ssh server settings.

# Make SSH auth socket location more predictable, so it works with tmux/screeen.
# To be fully effective, you should configure them appropriately:
# ~/.screenrc:  setenv SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock
# ~/.tmux.conf: setenv -g SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock
#               set -g update-environment "SSH_ASKPASS WINDOWID SSH_CONNECTION XAUTHORITY"
if test "$SSH_AUTH_SOCK" ; then
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi

# Set up xauth forwarding.
# Taken from the sshd(8) manpage.
if read proto cookie && [ -n "$DISPLAY" ]; then
    if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
        # X11UseLocalhost=yes
        echo add unix:`echo $DISPLAY | cut -c11-` $proto $cookie
    else
        # X11UseLocalhost=no
        echo add $DISPLAY $proto $cookie
    fi | xauth -q -
fi
