" GVim loads settings in this order (condensed from `:help gui-init`):
" 1. ALL non-GUI settings (see ~/.vim/vimrc)
" 2. System GUI configs
" 3. $GVIMINIT (as an Ex command line) or ~/.vim/gvimrc
" 4. (only if 'exrc' is set) $PWD/.gvimrc

set columns=84 lines=50
set guioptions=acegirLt

if exists('&guiheadroom')
    set guiheadroom=64
endif

if exists('&renderoptions')
    set renderoptions=type:directx,gamma:1.0,contrast:0.5,level:1,geom:1,renmode:4,taamode:1
endif


" Note: Most GUIs will let you `set guifont=*` to get a font chooser.
"set guifont=Noto\ Mono\ 9
"set guifont=Ubuntu\ Mono\ 10
"set guifont=DejaVu\ Sans\ Mono\ 9
"set guifont=Source\ Code\ Pro\ 10,Source_Code_Pro:h10:cANSI:qDRAFT

let s:fontface='Iosevka Fixed Medium'
let s:fontsize=11
if exists(':GuiFont')
    " nvim-qt does its own thing
    exec 'GuiFont' substitute(s:fontface, ' ', '\ ', 'g') .. ':h' .. s:fontsize
    "let g:dap='Did it with :GuiFont'
elseif exists("g:neovide")
    " neovide is remarkably picky about its font syntax,
    " so the catch-all below causes it to generate an error
    let &guifont=s:fontface .. ':h' .. s:fontsize
    "let g:dap='Did it with neovide &guifont'
else
    " Shotgun approach
    " XXX: Figure out if Windows needs anything special here
    "set guifont=Iosevka\ Fixed\ Medium\ 11,Iosevka_Fixed_Medium:h11:cANSI:qDRAFT
    let &guifont=s:fontface .. ' ' .. s:fontsize .. ',' .. substitute(s:fontface, ' ', '_', 'g') .. ':h' .. s:fontsize .. ':cANSI:qDCRAFT'
    "let g:dap='Fell back with &guifont'
endif

"--------------------------------
" Font test: oO0Q il1IL| sS$
" Hearts
" ☙ ♡ ♥ ❣ ❤ ❥ ❦ ❧ ⺖ ⺗ ⼼ 🎔 💑 💓 💔 💖 💗 💘 💙 💚 💛 💜 💝 💟 😍 😻
" Box drawing
" ─ ━ │ ┃ ┄ ┅ ┆ ┇ ┈ ┉ ┊ ┋ ┌ ┍ ┎ ┏ ┐ ┑ ┒ ┓ └ ┕ ┖ ┗ ┘ ┙ ┚ ┛ ├ ┝ ┞ ┟ ┠ ┡ ┢ ┣
" ┤ ┥ ┦ ┧ ┨ ┩ ┪ ┫ ┬ ┭ ┮ ┯ ┰ ┱ ┲ ┳ ┴ ┵ ┶ ┷ ┸ ┹ ┺ ┻ ┼ ┽ ┾ ┿ ╀ ╁ ╂ ╃ ╄ ╅ ╆ ╇
" ╈ ╉ ╊ ╋ ╌ ╍ ╎ ╏ ═ ║ ╒ ╓ ╔ ╕ ╖ ╗ ╘ ╙ ╚ ╛ ╜ ╝ ╞ ╟ ╠ ╡ ╢ ╣ ╤ ╥ ╦ ╧ ╨ ╩ ╪ ╫
" ╬ ╭ ╮ ╯ ╰ ╱ ╲ ╳ ╴ ╵ ╶ ╷ ╸ ╹ ╺ ╻ ╼ ╽ ╾ ╿
