set nocompatible
language en_US.UTF-8
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,latin1

" *** For vim-plug
"call plug#begin('~/.vim/plugged')
"Plug 'tpope/vim-fugitive'
"Plug 'tpope/vim-repeat'
"call plug#end()

" *** For vim-pathogen
source ~/.vim/bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

syntax on

let mapleader=" "
nnoremap <Leader>h :noh<CR>

set backspace=indent,eol,start
set autoindent
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set ruler
set hlsearch

set scrolloff=10

set pastetoggle=<F9>


set list listchars=tab:>·,trail:·,extends:>

if (&term == 'xterm' || &term =~? '^screen')
    set t_Co=256
endif

set background=dark
"colorscheme desert256
"colorscheme asu1dark
"colorscheme solarized

nnoremap <S-Insert> :set paste<CR>"*p:set nopaste<CR>
inoremap <S-Insert> <C-O>:set paste<CR><C-O>"*p<C-O>:set nopaste<CR>

" This lets us write plugins in perl, but really slows down vim's startup
let home=expand('~')
let $PERL5LIB=home."/perl5/lib/perl5/x86_64-linux-gnu-thread-multi:".home."/perl5/lib/perl5"
perl use Vim::X;
perl Vim::X::source_function_dir("~/.vim/perl");

"echo "Cygwin vimrc loaded"
