#!/bin/sh
#
# see `man githooks`

IS_SQUASH="$1"

if [ -x "$HOME/bin/git-ctags" ] ; then
    # This doesn't work like I hoped, it only gets the changes from
    # the last commit of the branch to the current
    #"$HOME/bin/git-ctags" MERGE_HEAD..HEAD &

    # For now, the best thing is to just re-generate ctags
    "$HOME/bin/git-ctags" &
fi
