#!/bin/bash

: ${TMUX_VERSION:?TMUX_VERSION not set}

# Tmux configuration that may be version-dependent goes here
# to keep my main .tmux.conf file from getting too messy.
# (That's less frequent now that I'm only interested in 2.x versions)

# This isn't really version specific, it's just cool: per-server colours.
# defaults in case str2colour.py doesn't work
foreground=black
background=green
complement=brightyellow

while read desc xcol col ; do
    eval $desc=\'"$col"\'
done < <(str2colour.py $HOSTNAME)

if vercmp.pl $TMUX_VERSION -lt 2.6 ; then
    tmux set -wg window-status-bg "$background"
    tmux set -wg window-status-fg "$foreground"
    tmux set -wg window-status-current-fg "$complement"
else
    tmux set -g status-style "fg=$foreground,bg=$background"
    tmux set -g window-status-style "fg=$foreground,bg=$background"
    tmux set -g window-status-current-style "fg=$complement"
fi

