# vim:filetype=tmux:fileencoding=utf-8:fileformat=unix:foldmethod=marker:
#
# Config and keybindings for https://github.com/christoomey/vim-tmux-navigator

pane_l="S-Left"
pane_r="S-Right"
pane_u="S-Up"
pane_d="S-Down"
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'

# This works on linux but not msys2
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"

# This should shortcut the common cases and work on msys2 but it doesn't
# https://github.com/christoomey/vim-tmux-navigator#faster-performance
is_vim="\
echo '#{pane_current_command}' | grep -iqE '^${vim_pattern}$' && exit 0
echo '#{pane_current_command}' | grep -iqE '^(bash|zsh|fish)$' && exit 1
ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"

# Switching panes
bind-key -T root $pane_l if-shell "$is_vim" 'send-keys $pane_l' 'select-pane -L'
bind-key -T root $pane_d if-shell "$is_vim" 'send-keys $pane_d' 'select-pane -D'
bind-key -T root $pane_u if-shell "$is_vim" 'send-keys $pane_u' 'select-pane -U'
bind-key -T root $pane_r if-shell "$is_vim" 'send-keys $pane_r' 'select-pane -R'
bind-key -T copy-mode-vi $pane_l select-pane -L
bind-key -T copy-mode-vi $pane_d select-pane -D
bind-key -T copy-mode-vi $pane_u select-pane -U
bind-key -T copy-mode-vi $pane_r select-pane -R

# Resizing panes
bind-key -T root M-$pane_l if-shell "$is_vim" 'send-keys M-$pane_l' 'resize-pane -L'
bind-key -T root M-$pane_d if-shell "$is_vim" 'send-keys M-$pane_d' 'resize-pane -D'
bind-key -T root M-$pane_u if-shell "$is_vim" 'send-keys M-$pane_u' 'resize-pane -U'
bind-key -T root M-$pane_r if-shell "$is_vim" 'send-keys M-$pane_r' 'resize-pane -R'
