#!/bin/bash

: ${TMUX_VERSION:?TMUX_VERSION not set}

sed -n '/^__DATA__$/,$p' "$0" | while read table key rest ; do
    [ -z "$table" ] && continue
    case "$table" in
        __DATA__)   continue ;;
        \#*)        continue ;;
    esac

    if vercmp.pl $TMUX_VERSION -lt 2.4 ; then
        # Copy my bindings as-is from below
        if [ "$rest" = "NONE" ] ; then
            tmux unbind-key -t $table $key
        else
            tmux bind-key -t $table $key $rest
        fi
    else
        # Tweak my bindings to the new key tables as per
        # https://github.com/tmux/tmux/issues/754
        table=$(echo $table | sed -e 's/\([^-]\+\)-\(.*\)/\2-mode-\1/')
        if [ "$rest" = "NONE" ] ; then
            tmux unbind-key -T $table %key
        else
            tmux bind-key -T $table $key send-keys -X $rest
        fi
    fi
done

exit 0
__DATA__

# Exit scrollback/copy mode
vi-copy Escape cancel

# Easier navigation when editing tmux's prompts
vi-edit C-Left previous-word
vi-edit C-Right next-word
# For terminals where BSpace sends ^?, Ctrl-BSpace sends ^H
vi-edit C-w NONE
vi-edit C-h delete-word

