#!/bin/sh
# This script is run by openbox-session on startup.
# openbox-session also runs the commands in ~/.config/autostart
# (the directory where GNOME/KDE put their session startup files).

if $(which tint2 > /dev/null 2>&1) ; then
    tint2 &
else
    term &
fi

compositor=$(which picom compton xcompmgr 2>/dev/null | head -n 1)
if [ -n "$compositor" ] ; then
    $compositor &
fi

A="${XDG_CONFIG_HOME:-$HOME/.config}/openbox/autostart.local"
test -x $A && $A
